version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - npm install -g pnpm
      - pnpm install --frozen-lockfile

  build:
    on-failure: ABORT
    commands:
      - pnpm --filter @monorepo/web validate:env
      - pnpm --filter @monorepo/web build
      - rm -rf apps/web/dist/**/*.js.map

  post_build:
    commands:
      - aws s3 sync --delete ./apps/web/dist s3://${DEPLOY_BUCKET}
      - aws cloudfront create-invalidation --distribution-id ${CF_ID} --paths /index.html