// Single source for the home view AND the generated SKILL.md (AXI
// principle 7). Edit here; skills/axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).
//
// Kept fully static/deterministic on purpose: this same content is baked
// into the committed SKILL.md by skill:gen, so it must not depend on local
// machine state (e.g. the contents of ~/.config/axi/config.json) or two
// runs on two machines would produce two different "identical" files.

import { homedir } from "node:os";
import { emitList } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";

export const DESCRIPTION =
  "Drives Collectshare's /v1/* external API — forms, questions, submissions, published datasets, and portal search — for AI agents and automation.";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

const COMMAND_TABLE: Array<{ command: string; summary: string }> = [
  { command: "auth open", summary: "print the /api-keys URL and the set-key follow-up" },
  { command: "auth set-key <key> [--base-url]", summary: "store an API key" },
  { command: "auth status [--verify]", summary: "show the configured key/base URL" },
  { command: "forms create <title> [--draft]", summary: "create a form (published by default)" },
  { command: "forms list", summary: "list your forms" },
  { command: "forms update <formId> <title>", summary: "update a form's details" },
  { command: "forms questions insert <formId> --file|--json", summary: "insert questions into a form" },
  { command: "submissions get <formId>", summary: "read your form's raw submissions" },
  { command: "datasets data <formId>", summary: "read a published dataset's rows" },
  { command: "portal search [--q] [--sort]", summary: "search published datasets" },
];

/**
 * Shared body of the home view; `tool` is how commands are written
 * ("axi" live, "npx -y axi" in the static skill).
 */
export function homeBody(tool: string): string {
  const table = emitList("commands", COMMAND_TABLE, ["command", "summary"]);
  const help = helpBlock([
    `${tool} auth open`,
    `${tool} forms list`,
    `${tool} <command> --help`,
  ]);
  return [table, help].join("\n");
}

export function renderHome(binPath: string): string {
  const header = `axi: ${collapseHome(binPath)} — ${DESCRIPTION}`;
  return [header, homeBody("axi")].join("\n");
}

/** Full tool reference for `axi --help`. */
export function rootHelpText(): string {
  const commands = emitList("commands", COMMAND_TABLE, ["command", "summary"]);
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `axi: ${DESCRIPTION}`,
    commands,
    flags,
    "examples[3]:",
    "  axi auth set-key cs_sk_... --base-url https://dev-api.collectshare.com.br",
    "  axi forms create \"Customer feedback\"",
    "  axi datasets data <formId>",
  ].join("\n");
}

/** The static SKILL.md: home content with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). Run the commands below with npx — no install needed.`,
    "",
    "No self-service key issuance exists yet: log in on the Collectshare web app, create a key at /api-keys" +
      " (pick the scopes you need — portal:read, forms:read, forms:write), then run `axi auth set-key`.",
    "",
    "```",
    homeBody("npx -y @collectshare/axi"),
    "```",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
