export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  NOT_ALLOWED = 'NOT_ALLOWED',

  // HTTP
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}
